services:
  - type: web
    name: global-skills-api
    env: docker
    rootDir: Backend
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_SSLMODE
        value: require
      - key: DB_HOST
        value: dpg-d717tedm5p6s738gp1m0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: globalskillsdb
      - key: DB_USERNAME
        value: joseph
      - key: DB_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false

  - type: web
    name: global-skills-frontend
    env: static
    rootDir: Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://global-skills-api.onrender.com
