services:
  - type: web
    name: global-skills-api
    env: docker
    rootDir: Backend
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://global-skills.onrender.com
      - key: APP_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://global-skills.vercel.app
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_SSLMODE
        value: require
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SANCTUM_STATEFUL_DOMAINS
        value: global-skills.vercel.app
      - key: SESSION_DRIVER
        value: database

  - type: web
    name: global-skills-frontend
    env: static
    rootDir: Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://global-skills.onrender.com
